#ifndef DEFINITIONS_H
#define DEFINITIONS_H

#include <DHT.h>
// PINES DEL SENSOR ULTRASONICO
#define PIN_TRIG 5
#define PIN_ECHO 4
// PIN DEL SENSOR DE TEMPERATURA Y HUMEDAD
#define DHT_PIN 2
#define DHT_TYPE DHT11
// PIN DEL SENSOR LDR
#define LDR_PIN A1
// PIN DEL SENSOR DE AUIRE
#define MQ135_PIN A0
// PIN DEL VENTILADOR
#define FAN_PIN 7
// PIN DEL LED
#define LED_PIN 6

// UMBRALES
#define MIN_DISTANCE 100
#define MIN_TEMPERATURE 30
#define MIN_CO2 100

// CICLOS
#define CYCLE_ONE 1
#define CYCLE_TWO 2

// TIEMPO DE TEMPORIZADOR
#define TIMER_LIMIT_LIGHT 20

#endif